// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more
// letter at a random position.

// Return the letter that was added to t.

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"

// Constraints:

// 0 <= s.length <= 1000
// t.length == s.length + 1
// s and t consist of lowercase English letters.

// So, here also let's say our character are:
// s = abc
// t = cabx

// if we take XOR of every character. all the n character of s "abc" is similar to n character of t "cab". So, they will cancel each other. 
// And we left with our answer.

// s =   abc
// t =   cbax
// ------------
// ans -> x
// -----------

class Solution {
  public char findTheDifference(String s, String t) {
    char c = 0;
    for (char cs : s.toCharArray())
      c ^= cs;
    for (char ct : t.toCharArray())
      c ^= ct;
    return c;
  }
}